name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1
        with: # Set the secret as an input
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        env: # Set the secret in the env
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag leakingmemory/alpine-openssh:latest
      - name: Push to Docker Hub build image
        run: docker push leakingmemory/alpine-openssh:latest

